### PR TITLE
TwoPaneLayout dependencies and package path update

### PR DESCRIPTION
**Pull request by joyl1216**
Change the package path to avoid "import com.microsoft.device.dualscreen.twopanelayout.TwoPaneLayout" and use "import com.microsoft.device.dualscreen.TwoPaneLayout" instead

### CODE REVIEW

**Comment by CesarValiente** [comment]
Hey Joy, 

I think this is not correct, since you are moving from:
`com.microsoft.device.dualscreen.twopanelayout` (common library name package that we use for all our libs + **specific** library package/domain)
to
`com.microsoft.device.dualscreen` (without defining a **specific** library package/domain) 

If I'm correct, basically you are saying that this library's **classes** are directly under `com.microsoft.device.dualscreen` without defining a library "package/domain".

Even when the published artifact will still keep the full **groupId** -> `com.microsoft.device.dualscreen`, and **artifactId** -> `twopanelayout`, with this change, the package that the library uses internally doesn't match with that, and there is not an `artifactId` or call it `library group` for this library.

e.g. in the android sdk libs (artifacts) we use `com.microsoft.device.dualscreen` as **groupId** for all libs, and an **artifactIds** such as `tabs`, `bottomnavigation`, etc. that **also match** internally with the package names these libraries have, e.g. `com.microsoft.device.dualscreen.tabs` or `com.microsoft.device.dualscreen.bottomnavigation`, etc.

With this change, twopanelayout classes will be orphaned of having a **specific package** to pend from.

**Review by CesarValiente — CHANGES_REQUESTED** [review]
Hey Joy, 

I think this is not correct, since you are moving from:
`com.microsoft.device.dualscreen.twopanelayout` (common library name package that we use for all our libs + **specific** library package/domain) to `com.microsoft.device.dualscreen` (**without** defining a **specific** library package/domain) 

If I'm correct, basically you are saying that this library's **classes** are directly under `com.microsoft.device.dualscreen` without defining a library "package/domain".

Even when the published artifact will still keep the full **groupId** -> `com.microsoft.device.dualscreen`, and **artifactId** -> `twopanelayout`, with this change, the package that the library uses internally doesn't match with that, and there is not an `artifactId` or call it `library group` for this library.

e.g. in the android sdk libs (artifacts) we use `com.microsoft.device.dualscreen` as **groupId** for all libs, and an **artifactIds** such as `tabs`, `bottomnavigation`, etc. that **also match** internally with the package names these libraries have, e.g. `com.microsoft.device.dualscreen.tabs` or `com.microsoft.device.dualscreen.bottomnavigation`, etc.

With this change, twopanelayout classes will be orphaned of having a **specific package** to pend from.

**Comment by joyl1216** [comment]
@CesarValiente the reason I update the package path is because `com.microsoft.device.dualscreen.twopanelayout.TwoPaneLayout` seems a little bit redundant to me, compared to `com.microsoft.device.dualscreen.ScreenInfo`.  I agree that `groupId` + `artifactId` makes more sense, than just putting everything under `com.microsoft.device.dualscreen`. I will revert the change.

**Review by CesarValiente — APPROVED** [review]
Thanks for handling this Joy! :-)

**Pull request merged**
