### PR TITLE
Update Compose version && Add some animation

### PR DESCRIPTION
**Pull request by Nthily**

### CODE REVIEW

**Comment by Nthily** [comment]
I've added some small animations to ComposeGalley

it looks like this:

demo

**Comment by Nthily** [comment]
demo

**Comment by joyl1216** [comment]
Hi Nthily, 

Nice to e-meet you!

Thank you for your interest and contribution to our project. The animation change you made is pretty cool. 👍   It is so easy to build animation with Compose, right? That's why we all like this new UI toolkit. 

We just bumped all the dependencies to the latest version with a complete verification. Sometimes we just forgot to do that. Appreciate your reminder. If you merge the Main branch back to yours or rebase your branch on top of the Main one, you will get the change.

Your pull request failed in our pipeline checking due to some small issues in the code style. We are following the default rules for lint and ktlint. You can find more details from [https://kotlinlang.org](https://kotlinlang.org/docs/coding-conventions.html#names-for-backing-properties) and [Kotlin style guide](https://developer.android.com/kotlin/style-guide). If you can address that, I am happy to merge your pull request.

Welcome to Jetpack Compose community and Microsoft Dual-screen development group!

Regards,
Joy

**Comment by Nthily** [comment]
> Hi Nthily,
> 
> Nice to e-meet you!
> 
> Thank you for your interest and contribution to our project. The animation change you made is pretty cool. 👍 It is so easy to build animation with Compose, right? That's why we all like this new UI toolkit.
> 
> We just bumped all the dependencies to the latest version with a complete verification. Sometimes we just forgot to do that. Appreciate your reminder. If you merge the Main branch back to yours or rebase your branch on top of the Main one, you will get the change.
> 
> Your pull request failed in our pipeline checking due to some small issues in the code style. We are following the default rules for lint and ktlint. You can find more details from [https://kotlinlang.org](https://kotlinlang.org/docs/coding-conventions.html#names-for-backing-properties) and [Kotlin style guide](https://developer.android.com/kotlin/style-guide). If you can address that, I am happy to merge your pull request.
> 
> Welcome to Jetpack Compose community and Microsoft Dual-screen development group!
> 
> Regards,
> Joy

Thank you!! , I found that it was some minor formatting errors, which I have fixed
 Is this where Microsoft Dual-screen development group is? 🙂

**Pull request closed without merging**
