### PR TITLE
Create a new app

### PR DESCRIPTION
**Pull request by Nthily**

### CODE REVIEW

**Comment by CesarValiente** [comment]
Hey @Nthily thanks for your work here! 
Whenever you finish the draft, can you please attach some screenshots (e.g. single screen, dual-screen) and add a detailed description?

Thanks,
Cesar

**Comment by Nthily** [comment]
> Hey @Nthily thanks for your work here!
> Whenever you finish the draft, can you please attach some screenshots (e.g. single screen, dual-screen) and add a detailed description?
> 
> Thanks,
> Cesar

yes claro :)

**Comment by Nthily** [comment]
@CesarValiente 
Hola Cesar!, I've done the initial design and it looks like this:
demo

In dual screen mode, it can display both chat details and conversation list

In Single Screen mode, it will operate with the same logic as a normal phone

**Comment by Nthily** [comment]
@CesarValiente 
Hola Cesar!, I've done the initial design and it looks like this:
demo

In dual screen mode, it can display both chat details and conversation list

In Single Screen mode, it will operate with the same logic as a normal phone

**Comment by Nthily** [comment]
also in github action, I ran into this problem that I can't quite solve

VPOQR{CC%3$_QJ82R}VDC{9

i don't know what this is caused by

**Comment by Nthily** [comment]
In terms of file changes
1. I have added `hilt android`
2. modified Gradle version, 7.0.2 -> 7.1.0-alpha02 (because in 7.0.2 hilt seems to be unusable)

**Comment by joyl1216** [comment]
@Nthily thanks for your contribution. Before we move forward, I have few questions about your project. Hope you can help me understand better about your idea. 
1. Will your project become a full-functional chatting app? or just show the list-detail style of chatting UI?
2. Would you please let us know the whole plan or scope of your project? Is it completed already, or you would like to add more features after this PR?
3. What does the app look like when the device rotates in both dual-screen mode and single-screen mode?
4. Have you tested your project on other foldable emulators, such as the default emulator in Android Studio("6.7 Horizongtal Fold-in", or "7.6 Fold-in")?

**Comment by joyl1216** [comment]
@Nthily thanks for your contribution. Before we move forward, I have few questions about your project. Hope you can help me understand better about your idea. 
1. Will your project become a full-functional chatting app? or just show the list-detail style of chatting UI?
2. Would you please let us know the whole plan or scope of your project? Is it completed already, or you would like to add more features after this PR?
3. What does the app look like when the device rotates?
4. Have you tested your project on other foldable emulators, such as the default emulator in Android Studio()?

**Comment by Nthily** [comment]
@joyl1216 Hi joy ! thank for your question
1. i don't intend to write it as a full-featured app, I just want to show the effect,

2. So far, it's not finished, but im going to try to add some more fun stuff when I have time!

3. it looks like this:
demo

4. i haven't tested it in other similar devices

**Comment by joyl1216** [comment]
@Nthily Thanks for your answer. I like the chatting app idea and would like to know more about your "fun stuff". All the samples here are to showcase different app patterns on dual-screen/foldable development with Jetpack Compose. List-detail is one of the important patterns which can benefit the chatting scenario. But I am thinking more, since we've already had a simple List-detail sample here, "drag&drop", or "bubble button" ... may be good features to add. What do you think?

**Comment by Nthily** [comment]
@joyl1216 Hi joy ! long time no see, i've been a little busy lately, i read ur reply and it makes sense, `List-Detail` already has a similar app, my "fun stuff" is that I can create a little bot-like auto-response on my demo app, for example when I send `Surface Duo` with Windows, it gives me a Surface Duo website link, etc...

but after reading ur reply, I dont feel my demo app is necessary anymore, and i probably wont have time to keep improving it in the near future, maybe i can consider the "drag&drop", or "bubble button" you mentioned, but i still dont quite understand how it works?

**Pull request closed without merging**
