### PR TITLE
List Detail sample

### PR DESCRIPTION
**Pull request by joyl1216**
e
s

### CODE REVIEW

**Comment by Mehul1995** [comment]
@joyl1216 LGTM!

**Comment by Mehul1995** [comment]
image

**Comment by Mehul1995** [comment]
image

**Comment by Mehul1995** [comment]
image

**Comment by joyl1216** [comment]
Screenshot_1611612284
Screenshot_1611612315
@Mehul1995  updated

**Comment by Mehul1995** [comment]
LGTM! 💯

**Review by CesarValiente — APPROVED** [review]
LGTM! Thanks Joy!

**Pull request merged**
